table "product_categories" {
  "id" int [pk, increment]
  "name" varchar(30)
}

table "products" {
  "id" uuid [pk]
  "name" varchar(255)
  "description" varchar
  "image" varchar
  "categoryId" int
  "quantityState" varchar(30)
  "productState" varchar(30)
  "price" decimal
}

ref: product_categories.id < products.categoryId