spring:
  sql.init.mode: always

  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: warehouse

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/commerce_warehouse
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:password}