spring:
  sql.init.mode: always

  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: warehouse

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6543/smart_home
    #url: jdbc:postgresql://localhost:5432/smart_home
    username: dbuser
    password: 12345