collector:
  kafka:
    producer:
      properties:
        bootstrap.servers: localhost:9092
        key.serializer: org.apache.kafka.common.serialization.StringSerializer
        value.serializer: kafka.GeneralAvroSerializer
      topics:
        sensors-events: telemetry.sensors.v1
        hubs-events: telemetry.hubs.v1

grpc:
  server:
    port: 59091

logging:
  level:
    ru.yandex.practicum.telemetry: DEBUG